# Generated by Django 4.1.4 on 2022-12-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_alter_pokemon_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='generacion',
            field=models.CharField(default='sin grupo', max_length=20),
        ),
    ]
