# Generated by Django 4.1.3 on 2022-11-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('tipo', models.CharField(max_length=12)),
                ('generacion', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
