# Generated by Django 4.1.3 on 2022-11-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='tipo',
            field=models.CharField(max_length=40),
        ),
    ]
