# Generated by Django 4.1.3 on 2022-11-17 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_alter_pokemon_generacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='generacion',
            field=models.CharField(default='sin grupo', max_length=5),
        ),
    ]
