# Generated by Django 4.1.3 on 2022-12-01 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='dni',
            field=models.CharField(default='00000000', max_length=8),
        ),
        migrations.AddField(
            model_name='owner',
            name='vigente',
            field=models.BooleanField(default=True),
        ),
    ]
