# Generated by Django 4.1.4 on 2022-12-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_owner_dni_owner_vigente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
